/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type BankCreated = ContractEventLog<{
  daoAddress: string;
  extensionAddress: string;
  0: string;
  1: string;
}>;

export interface BankFactory extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): BankFactory;
  clone(): BankFactory;
  methods: {
    identityAddress(): NonPayableTransactionObject<string>;

    create(
      dao: string,
      maxExternalTokens: number | string | BN
    ): NonPayableTransactionObject<void>;

    getExtensionAddress(dao: string): NonPayableTransactionObject<string>;
  };
  events: {
    BankCreated(cb?: Callback<BankCreated>): EventEmitter;
    BankCreated(
      options?: EventOptions,
      cb?: Callback<BankCreated>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "BankCreated", cb: Callback<BankCreated>): void;
  once(
    event: "BankCreated",
    options: EventOptions,
    cb: Callback<BankCreated>
  ): void;
}
