/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type ERC20TokenExtensionCreated = ContractEventLog<{
  daoAddress: string;
  extensionAddress: string;
  0: string;
  1: string;
}>;

export interface ERC20TokenExtensionFactory extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): ERC20TokenExtensionFactory;
  clone(): ERC20TokenExtensionFactory;
  methods: {
    identityAddress(): NonPayableTransactionObject<string>;

    create(
      dao: string,
      tokenName: string,
      tokenAddress: string,
      tokenSymbol: string,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    getExtensionAddress(dao: string): NonPayableTransactionObject<string>;
  };
  events: {
    ERC20TokenExtensionCreated(
      cb?: Callback<ERC20TokenExtensionCreated>
    ): EventEmitter;
    ERC20TokenExtensionCreated(
      options?: EventOptions,
      cb?: Callback<ERC20TokenExtensionCreated>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(
    event: "ERC20TokenExtensionCreated",
    cb: Callback<ERC20TokenExtensionCreated>
  ): void;
  once(
    event: "ERC20TokenExtensionCreated",
    options: EventOptions,
    cb: Callback<ERC20TokenExtensionCreated>
  ): void;
}
