/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface IVoting extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IVoting;
  clone(): IVoting;
  methods: {
    getAdapterName(): NonPayableTransactionObject<string>;

    startNewVotingForProposal(
      dao: string,
      proposalId: string | number[],
      data: string | number[]
    ): NonPayableTransactionObject<void>;

    getSenderAddress(
      dao: string,
      actionId: string,
      data: string | number[],
      sender: string
    ): NonPayableTransactionObject<string>;

    voteResult(
      dao: string,
      proposalId: string | number[]
    ): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
