/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface ManagingContract extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): ManagingContract;
  clone(): ManagingContract;
  methods: {
    proposals(
      arg0: string,
      arg1: string | number[]
    ): NonPayableTransactionObject<{
      adapterOrExtensionId: string;
      adapterOrExtensionAddr: string;
      updateType: string;
      flags: string;
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    submitProposal(
      dao: string,
      proposalId: string | number[],
      proposal: [
        string | number[],
        string,
        number | string | BN,
        number | string | BN,
        (string | number[])[],
        (number | string | BN)[],
        string[],
        (number | string | BN)[]
      ],
      data: string | number[]
    ): NonPayableTransactionObject<void>;

    processProposal(
      dao: string,
      proposalId: string | number[]
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
