/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface OnboardingContract extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): OnboardingContract;
  clone(): OnboardingContract;
  methods: {
    proposals(
      arg0: string,
      arg1: string | number[]
    ): NonPayableTransactionObject<{
      id: string;
      unitsToMint: string;
      amount: string;
      unitsRequested: string;
      token: string;
      applicant: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string;
    }>;

    units(
      arg0: string,
      arg1: string,
      arg2: string
    ): NonPayableTransactionObject<string>;

    configureDao(
      dao: string,
      unitsToMint: string,
      chunkSize: number | string | BN,
      unitsPerChunk: number | string | BN,
      maximumChunks: number | string | BN,
      tokenAddr: string
    ): NonPayableTransactionObject<void>;

    submitProposal(
      dao: string,
      proposalId: string | number[],
      applicant: string,
      tokenToMint: string,
      tokenAmount: number | string | BN,
      data: string | number[]
    ): NonPayableTransactionObject<void>;

    processProposal(
      dao: string,
      proposalId: string | number[]
    ): PayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
