/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type MemberRagequit = ContractEventLog<{
  daoAddress: string;
  memberAddr: string;
  burnedUnits: string;
  burnedLoot: string;
  initialTotalUnitsAndLoot: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;

export interface RagequitContract extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): RagequitContract;
  clone(): RagequitContract;
  methods: {
    ragequit(
      dao: string,
      unitsToBurn: number | string | BN,
      lootToBurn: number | string | BN,
      tokens: string[]
    ): NonPayableTransactionObject<void>;
  };
  events: {
    MemberRagequit(cb?: Callback<MemberRagequit>): EventEmitter;
    MemberRagequit(
      options?: EventOptions,
      cb?: Callback<MemberRagequit>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "MemberRagequit", cb: Callback<MemberRagequit>): void;
  once(
    event: "MemberRagequit",
    options: EventOptions,
    cb: Callback<MemberRagequit>
  ): void;
}
