/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface VotingContract extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): VotingContract;
  clone(): VotingContract;
  methods: {
    ADAPTER_NAME(): NonPayableTransactionObject<string>;

    isActiveMember(
      dao: string,
      _addr: string
    ): NonPayableTransactionObject<boolean>;

    votes(
      arg0: string,
      arg1: string | number[]
    ): NonPayableTransactionObject<{
      nbYes: string;
      nbNo: string;
      startingTime: string;
      blockNumber: string;
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    getAdapterName(): NonPayableTransactionObject<string>;

    configureDao(
      dao: string,
      votingPeriod: number | string | BN,
      gracePeriod: number | string | BN
    ): NonPayableTransactionObject<void>;

    startNewVotingForProposal(
      dao: string,
      proposalId: string | number[],
      arg2: string | number[]
    ): NonPayableTransactionObject<void>;

    getSenderAddress(
      arg0: string,
      arg1: string,
      arg2: string | number[],
      sender: string
    ): NonPayableTransactionObject<string>;

    submitVote(
      dao: string,
      proposalId: string | number[],
      voteValue: number | string | BN
    ): NonPayableTransactionObject<void>;

    voteResult(
      dao: string,
      proposalId: string | number[]
    ): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
